DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
    "BOOK_ID" VARCHAR2 (50 CHAR) NOT NULL,
    "NAME" VARCHAR2 (50 CHAR) NOT NULL,
    "IMAGE" VARCHAR2 (100 CHAR) NOT NULL,
    "AUTHOR" VARCHAR2 (50 CHAR) NOT NULL,
    "CATEGORY" VARCHAR2 (50 CHAR) NOT NULL,
    "CONTENT" VARCHAR2 (200 CHAR) NOT NULL,
    PRIMARY KEY ("BOOK_ID")
);


DROP TABLE IF EXISTS API_KEY;

CREATE TABLE API_KEY (
    "ID" BIGINT NOT NULL IDENTITY,
    "KEY" VARCHAR2 (50 CHAR) NOT NULL,
    PRIMARY KEY("ID")
)
